### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by reinhold-willcox** [frangoud/ZoteroDuplicatesMerger#1]
Hi, this plugin looks really useful, but I'm new to Zotero plugins generally. Could you add install instructions to the README?

**Comment by frangoud** [comment]
I've updated the readme file to include instructions related to the installation. Additional information can be found in the official plugins webpage of Zoero: https://www.zotero.org/support/plugins

**Comment by reinhold-willcox** [comment]
Thanks for the quick response!
