### ISSUE TITLE
Not compatible with Zotero 7

### ISSUE THREAD

**Issue by quinn-p-mchugh** [frangoud/ZoteroDuplicatesMerger#14]
Hi all, creating this issue as an extension of #12 & #9. I am not the original developer of this add-on - I'm just an enthusiastic user and potential contributor that would love to see this plugin made compatible with Zotero 7.

**I'm happy to offer $50 to the developer that is able to complete a majority of this work.**

# Background
[Zotero 7 is now in beta and will be released sometime in 2024](https://www.zotero.org/support/dev/zotero_7_for_developers#:~:text=Zotero%207%2C%20which,changes%20between%20versions.). This update introduces breaking changes that will require all Zotero add-ons to be updated in order to maintain compatibility. This means some updates will have to be made to this plugin for it to be used with Zotero 7.
> Zotero 7, which will be released in 2024, includes a major internal upgrade of the Mozilla platform on which Zotero is based, incorporating changes from Firefox 60 through Firefox 115. This upgrade brings major performance gains, new JavaScript and HTML features, better OS compatibility and platform integration, and native support for Apple Silicon Macs.
> 
> While this upgrade required a massive rewrite of the Zotero code base and **will require many plugin changes due to technical changes in the Mozilla platform**, going forward we expect to keep Zotero current with Firefox Extended Support Release (ESR) versions, with comparatively fewer technical changes between versions.

# Summary of Updates Required
Zotero provides some [instructions for updating plugins to ensure compatibility with Zotero 7](https://www.zotero.org/support/dev/zotero_7_for_developers#:~:text=an%20incompatible%20version.-,Plugin%20Changes,-All%20Zotero%20plugins). 

Below, I've used an LLM to summarize the required updates. Depending on the architecture of this plugin, some of these updates may not be required. See the [Zotero 7 developer instructions](https://www.zotero.org/support/dev/zotero_7_for_developers#:~:text=an%20incompatible%20version.-,Plugin%20Changes,-All%20Zotero%20plugins) for more info.

## **A**: Manifest Files
**A1**. Replace install.rdf with manifest.json.
**A2**. Replace update.rdf with updates.json.

## **B**: Functionality Changes
**B1**. Transition from XUL Overlays to bootstrap.js for DOM manipulation.
**B2**. Replace chrome.manifest with runtime chrome registration.
**B3**. Update localization to Fluent (.ftl).
**B4**. Move default preferences to prefs.js in the plugin root.

## **C**: User Interface Changes
**C1**. Use Zotero's built-in function to register preference panes.
**C2**. Directly bind preference keys in preference panes (remove <preference> tags).
**C3**. Use official APIs for custom item tree columns, item pane sections, and reader event handlers.

## **D**: Platform Changes
**D1**. Replace Mozilla CSS with standard CSS.
**D2**. Update module import lines.
**D3**. Handle changes to Zotero platform APIs.
**D4**. Replace the use of OS.File, OS.Path, and OS.Constants.Path with IOUtils and PathUtils.
**D5**. Use Zotero.isWin/isMac/isLinux for platform conditionals, Zotero.getOSVersion() for the OS version, and Zotero.arch for the architecture.

# Contributing
Any and all contributions are appreciated towards upgrading this incredibly useful add-on to Zotero 7.

If you are interested in contributing to this effort, please:
1. Comment which of the updates above you intend to implement
2. Post a link to the fork where you're working from
3. Ask any clarifying questions that others might be able to help answer.

Thank you for your interest!

**Comment by algora-pbc** [comment]
💎 **quinn-p-mchugh0** is offering a **$50** bounty for this issue
👉 Got a pull request resolving this? Claim the bounty by adding `@algora-pbc /claim #14` in the PR body and joining algora.io

**Comment by adilkadivala** [comment]
Hi, Adil Here, I want to work on this issue,, assign me this issue.

**Comment by quinn-p-mchugh** [comment]
Hi @adilkadivala ! Thanks for your interest. Please feel free to submit a pull request, as instructed by the Algora bot above.

**Comment by adilkadivala** [comment]
@algora-pbc /claim #14

**Comment by adilkadivala** [comment]
I have implemented  A: Manifest Files,  and pull is created

my fork link [here](https://github.com/adilkadivala/ZoteroDuplicatesMerger)

@algora-pbc /claim #14

/claim #14

**Comment by quinn-p-mchugh** [comment]
Hi @adilkadivala,

Thanks for spearheading updates A1 and A2! In order to claim this bounty, though, parts B, C, and D will also need to be addressed.

If you wish to continue, please submit a single pull request will all of the above updates and include `@algora-pbc /claim #1` in the pull request description.

**Comment by ChenglongMa** [comment]
Hi @quinn-p-mchugh,

I have implemented a plugin to detect and manage duplicates for both Zotero 6 and 7.
If you are interested, please check it out to see if it meets your needs.

Here is the project: [zoplicate](https://github.com/ChenglongMa/zoplicate).

Thanks!

Best regards,
Chenglong

----
@algora-pbc /claim https://github.com/frangoud/ZoteroDuplicatesMerger/issues/14

**Comment by quinn-p-mchugh** [comment]
@ChenglongMa 
Amazing!!! Thanks for your work, ChenglongMa. Excited to try this out (and clean up my library!)

I'm happy to reward you the bounty, but in order to do so, I'll need you to create a quick pull request on this repository with `@algora-pbc /claim #14` in the body. It doesn't need to contain any substantial changes - just something to that can trigger the Algora bot.

Are you able to do that?

Without that pull request, Algora will not let me send the reward to you.
![image](https://github.com/user-attachments/assets/f0d40246-4741-435d-8754-6210a24ed5ba)

**Comment by quinn-p-mchugh** [comment]
Thank you for your work as well, @adilkadivala, and I'm sorry I'm not able to reward you the bounty.

You might be interested in contributing to @ChenglongMa's project above.

**Comment by ChenglongMa** [comment]
> @ChenglongMa Amazing!!! Thanks for your work, ChenglongMa. Excited to try this out (and clean up my library!)
> 
> I'm happy to reward you the bounty, but in order to do so, I'll need you to create a quick pull request on this repository with `@algora-pbc /claim #14` in the body. It doesn't need to contain any substantial changes - just something to that can trigger the Algora bot.
> 
> Are you able to do that?
> 
> Without that pull request, Algora will not let me send the reward to you. ![image](https://private-user-images.githubusercontent.com/40648753/357544970-f0d40246-4741-435d-8754-6210a24ed5ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODc0NjgsIm5iZiI6MTcyMzU4NzE2OCwicGF0aCI6Ii80MDY0ODc1My8zNTc1NDQ5NzAtZjBkNDAyNDYtNDc0MS00MzVkLTg3NTQtNjIxMGEyNGVkNWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDIyMTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZjRhYjAwYWMwZmUyMmQ1YmIzMjcxNmVhNWY0NzExNDkzZmE2NGRhMmVlYmI2OWE4MWYwZWU0ODgwYWJlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SgEezkV7y68x5X9dENraHVdxWHpUFFaxsUNJNZJqYWY)

@quinn-p-mchugh

Thanks for your kind words 😊! I've created a placeholder pull request for this issue.

**Comment by quinn-p-mchugh** [comment]
Closing. Check out [zoplicate](https://github.com/ChenglongMa/zoplicate) - works great with Zotero 7!
